version: '3'

services:
  app:
    build: ./

    container_name: 'ematch'
    image: ematch

    ports:
      - '8080:8080'

    links:
      - database:database

    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - NODE_ENV=production

  database:
    container_name: 'database'
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'MainDatabase'
      MYSQL_USER: 'MainUser'
      MYSQL_PASSWORD: 'dkfjsdofnsofnmno5j84584nknvkIDJFIDOFJODS&&&***&(hjhdfkldf'
      MYSQL_ROOT_PASSWORD: 'root'
      LANG: C.UTF-8
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]

volumes:
  database:
    # driver: local
